/*
Key Insights:

Total Sales and Profit show a positive relationship, indicating consistent business growth.
 Total sales recorded: 22,95,455 showing strong overall performance.
 Total profit recorded= 2,85,911

Consumer Segment leads in both sales(11,60,393) and profit (133,875).

Home Office Segment has the lowest sales(4,29,202) and profit(60,140).


Technology is the top-performing category highest sales(8,35,475) & profit(1,45,308)

Furniture has the lowest profit(18409) among all categories.

Office supplies has the lowest sales: 7,18,184 among all categories.

As per the discount analysis 

Minimum Discount: 0

Maximum Discount: 0.8

Average Discount: 0.156

Total cities with:

Minimum Discount: 336

Maximum Discount: 52

Maximum discounts are mainly in Central Region  (STATES= Texas, Illinois)

West Region generates highest sales(731,592); South Region generate the lowest sales (395,215)

Sales contribution by region : West (31.58%) > East (29.52%) > Central > South

Top performing location by sales: New York City (East Region)

California state contributes the highest overall profit

Technology has the highest profit margin (17.39%)

Furniture has the lowest profit margin (2.48%)

Some products have high availability but low sales → possible low demand
*/

/*
conculsion 

The analysis showing  that this  business is doing well mainly because of the Technology category and Consumer segment. 
These bring the most sales and profit.

The West and East regions are performing better than other regions.

However, high discounts (especially in Central region) are reducing profit. Also, the Furniture category is not giving  so much profit.

To improve that , the company should focus more on high-performing areas and reduce unnecessary discounts.

What actions i will take after my analysis 
The Furniture category has low profit, so discounts should be reduced there. 
The Technology category already has high demand, so heavy discounts are not necessary.
In the Central region, discounts should be optimized.
We should focus more on high-performing segments and apply improvement strategies to low-performing products.

*/